apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-logger
  template:
    metadata:
      labels:
        app: flask-logger
    spec:
      containers:
      - name: flask-logger
        image: flask-logger:latest
        ports:
        - containerPort: 5000

